azureTenant: nav.no
kafkaPool: nav-prod
environment: prod
replicas_min: 6
replicas_max: 6
db_tier: db-custom-1-3840
db_diskSize: 10
env:
  SPRING_PROFILES_ACTIVE: default
  YRKESSKADE_URL: http://yrkesskade-saker.yrkesskade
  YRKESSKADE_AAD_CLIENT_ID: prod-gcp.yrkesskade.yrkesskade-saker